spring.application.name=voting-system

# Configuración del Puerto del Servidor
server.port=8081

# Conexión a PostgreSQL 
spring.datasource.url=jdbc:postgresql://localhost:5432/voting_db
spring.datasource.username=postgres
spring.datasource.password="your_password_here"
spring.datasource.driver-class-name=org.postgresql.Driver

# Basic Auth Credentials
spring.security.user.name=${ADMIN_USER:admin}
spring.security.user.password=${ADMIN_PASSWORD:admin123}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect